service: my-service

provider:
  name: aws
  runtime: python3.8

  functions:
  hello:
    handler: handler.hello

    plugins:
  - serverless-python-requirements
  - serverless-offline

  custom:
  pythonRequirements:
    dockerizePip: non-linux